### ISSUE TITLE
How to clean up spill again

### ISSUE THREAD

**Issue by spacekookie** [sparr/factorio-mod-wreckage-pollution#5] opened 2023-04-18 14:49 UTC
Love this mod for fixing something that I thought was very unrealistic in the base game. However, I can't figure out how to clean up the spills. Is there a technology I haven't unlocked yet? I didn't see any documentation about this so apologies for opening a GH issue

**Comment by sparr** [comment] 2023-07-11 11:27
Fixed by https://github.com/sparr/factorio-mod-wreckage-pollution/commit/ea72b1658f576f111a2de302bc72ca75a4a1124d

Root cause was an arithmetic/logic bug triggered by all existing spills evaporating, then later new spills being created. This is fixed in the latest version. Sorry for the delay.

**Closed as completed by sparr** 2023-07-11 11:27 UTC
